apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sparky-fitness
resources:
  - namespace.yaml
  - db.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  - externalsecret.yaml
  - smtp-externalsecret.yaml
  - replicationsource.yaml
