apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vaultwarden

resources:
  - httproute-internal.yaml
  - externalsecret.yaml
  - smtp-externalsecret.yaml
  - db

helmCharts:
  - name: vaultwarden
    repo: https://guerzon.github.io/vaultwarden
    version: 0.34.6
    releaseName: vaultwarden
    valuesFile: values/values.yaml
