database:
  type: "postgresql"
  existingSecret: "vaultwarden-cnpg-cluster-app"
  existingSecretKey: "uri"

replicas: 1

storage:
  data:
    name: "vaultwarden-data"
    size: "5Gi"
    class: "longhorn"
    accessMode: "ReadWriteOnce"

adminToken:
  existingSecret: "vaultwarden"
  existingSecretKey: "ADMIN_TOKEN"
  value: ""

smtp:
  host: smtp.gmail.com
  from: "no-reply@monederobox.dev"
  fromName: "Vaultwarden"
  security: "force_tls"
  port: 465
  existingSecret: "vaultwarden-smtp"
  username:
    existingSecretKey: "SMTP_USER"
  password:
    existingSecretKey: "SMTP_PASSWORD"

# Enable the web vault
webVaultEnabled: "true"

# Set the domain
domain: "https://vault.monederobox.dev"

# Allow signups but require verification
signupsAllowed: false
signupsVerify: true
adminRateLimitSeconds: 15
