apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: zot

resources:
  - namespace.yaml
  - externalsecret.yaml
  - httproute.yaml

helmCharts:
  - name: zot
    repo: https://zotregistry.dev/helm-charts
    releaseName: zot
    version: "0.1.95"
    namespace: zot
    valuesFile: values/values.yaml
