apiVersion: apps/v1
kind: Deployment
metadata:
  name: suwayomi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: suwayomi
  template:
    metadata:
      labels:
        app: suwayomi
    spec:
      containers:
        - name: suwayomi
          image: ghcr.io/suwayomi/suwayomi-server:v2.1.2007
          env:
            - name: TZ
              value: "Etc/UTC"
            # - name: FLARESOLVERR_ENABLED
            #   value: "true"
            # - name: FLARESOLVERR_URL
            #   value: "http://flaresolverr:8191"
            - name: AUTH_MODE
              value: "none"
            - name: AUTH_USERNAME
              value: "admin"
            - name: AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: suwayomi-secrets
                  key: AUTH_PASSWORD
          ports:
            - containerPort: 4567
          volumeMounts:
            - name: data
              mountPath: /home/suwayomi/.local/share/Tachidesk
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: suwayomi-data
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: flaresolverr
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: flaresolverr
#   template:
#     metadata:
#       labels:
#         app: flaresolverr
#     spec:
#       containers:
#         - name: flaresolverr
#           image: ghcr.io/thephaseless/byparr:v2.1.1960
#           environment:
#             - name: TZ
#               value: "Etc/UTC"
#           ports:
#             - containerPort: 8191
