apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wger

resources:
  - httproute.yaml
  - namespace.yaml
  - db

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: wger-app
      spec:
        template:
          spec:
            containers:
              - name: wger
              - env:
                - name: CSRF_TRUSTED_ORIGINS
                  value: https://wger.monederobox.dev

helmCharts:
  - name: wger
    repo: https://wger-project.github.io/helm-charts
    releaseName: wger
    version: "0.2.4"
    namespace: wger
    valuesFile: values/values.yaml
