apiVersion: v1
kind: Secret
metadata:
  name: pocket-id-restic-config
stringData:
  RESTIC_REPOSITORY: s3:https://hel1.your-objectstorage.com/revachol/backups/pocket-id-pvc
  RESTIC_PASSWORD: ""
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
